### ISSUE TITLE
Use same command window?

### ISSUE THREAD

**Issue by diego898** [jessebikman/Sublime-Text-2-build-Matlab-code#11]
This opens a new matlab command window every time. Is it possible to use one thats already open?

Im using sublime text 3 with matlab 2013b on windows 8

**Comment by jessebikman** [comment]
I think that's outside of the scope of what this script seeks to accomplish. However, that isn't a big deal because the [SublimeREPL](https://github.com/wuub/SublimeREPL) project has a [MATLAB config](https://github.com/wuub/SublimeREPL/tree/master/config/Matlab). Try it out!

**Comment by diego898** [comment]
each command window is actually a separate instance of matlab, so multiple builds result in multiple opening/initializing/closing of matlab. 

Hello: I have tried that and it opens another command window as well :L
