### ISSUE TITLE
Opens Matlab each time I press ctrl+B

### ISSUE THREAD

**Issue by ghost** [jessebikman/Sublime-Text-2-build-Matlab-code#2]
I managed to get it to work on Windows 7 with Matlab 2011b. But the problem is whenever I build the code, it starts another Matlab window. Can it be fixed?

**Comment by jessebikman** [comment]
Have you tried using "-nodesktop", "-nosplash" flags? That didn't seem to work on my OS, but still worth a shot. That's how I invoke Matlab through Terminal since I don't generally feel obliged to deal with the sluggish GUI.

**Comment by changjian-k2k** [comment]
The same problem as m4hmoud. When I want to run a matlab script and there alreay exists a Matlab, it's better just run it in the existing Matlab than in a new one. Just like press F5 in matlab editor.

**Comment by jessebikman** [comment]
That's bizarre. Feel free to fork - I don't have a windows machine for testing.
