### ISSUE TITLE
Sublime error on os x 10.8.2 R2012a

### ISSUE THREAD

**Issue by pycckuu** [jessebikman/Sublime-Text-2-build-Matlab-code#4]
Mac os, matlab12a, sublime error:

[Errno 2] No such file or directory
[cmd:  [u'/Applications/Matlab/MATLAB_R2012a.app/bin/matlab', u'-nosplash', u'<advectiondiffusion.m']]
[dir:  /Volumes/UserHDD/igormarkelov/Documents/git/ScientificComputation/15-Spectral mehod implementation]
[path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/bin]
[Finished]

**Comment by pycckuu** [comment]
what this error means?

**Comment by jessebikman** [comment]
Looks like something doesn’t exist. What happens when you open a terminal window and run “/Applications/Matlab/MATLAB_R2012a.app/bin/matlab”?
