### ISSUE TITLE
Syntax error encountered

### ISSUE THREAD

**Issue by swaroopvedula** [jessebikman/Sublime-Text-2-build-Matlab-code#5]
Using Matlab_R2012b on Mac OS 10.8.2.

Encountering the following errors:
/Applications/MATLAB_R2012b.app/bin/matlab: eval: line 1710: syntax error near unexpected token `newline'
/Applications/MATLAB_R2012b.app/bin/matlab: eval: line 1710:`exec  "/Applications/MATLAB_R2012b.app/bin/maci64/../../Contents/MacOS/MATLAB_maci64"  -nosplash <'

Have others come across these errors? Suggestions on how to fix the build code?

Thank you!

**Comment by jessebikman** [comment]
Hey - I just updated for R2012b, check it out. It screws up if you attempt to delete variables, and can be somewhat dodge-y with GUIDE GUIs.
