### ISSUE TITLE
Is there ny way do not close window after running the script? and always run the script in this window of Matlab? OSX 10.8. Thank you in advance.

### ISSUE THREAD

**Issue by pycckuu** [jessebikman/Sublime-Text-2-build-Matlab-code#6]

**Comment by jfainberg** [comment]
I'm having a similar issue. Using Sublime Text 3 on OS X 10.9.1 with MATLAB 2013a, everything works fine, but the Figure window does not stay open, but close immediately. Any thoughts?

Thanks for your work!

**Comment by jessebikman** [comment]
Hey, I'm glad that you're able to use this plugin with a version of Sublime Text I've never used. 

My plugin isn't capable of running MATLAB code written for non-headless displays. If you can find the right JSON args, fork away!
