### ISSUE TITLE
Can't get it working with R2012b

### ISSUE THREAD

**Issue by joaocandre** [jessebikman/Sublime-Text-2-build-Matlab-code#7]
I'm trying to use this together with R2012b, doesn't work, and the strange thing is that Sublime's console has no output. Is that normal behaviour since it's only supposed to work with R2012a or is there some additional problem?

**Comment by jessebikman** [comment]
Did you specify the correct Build System in Sublime Text 2? 

Are you on a Mac? 
Confirm that the path to your R2012b MATLAB binary is intact by opening a terminal window and typing 

```
/Applications/MATLAB_R2012b.app/bin/matlab
```

**Comment by joaocandre** [comment]
@jessebikman I am running Linux (Ubuntu), and I have the binary in /usr/local/MATLAB/R2012b/bin/matlab, and a symlink under /usr/bin. Yet, despite being able to call a function or script through the SO command line, Sublime's console shows no output.

**Comment by jessebikman** [comment]
Here, try this instead:

https://github.com/jessebikman/Sublime-Text-2-build-Matlab-code/blob/master/Linux-R2012b-Matlab.sublime-build
